repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: detect-aws-credentials
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: ['--branch', 'master']
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9
    hooks:
      - id: shellcheck
  - repo: git@github.com:thlorenz/doctoc
    rev: v1.4.0
    hooks:
      - id: doctoc
  - repo: git@github.com:PyCQa/pylint
    rev: pylint-2.5.3
    hooks:
      - id: pylint
